org: chdrdevelop
app: scraper-node
service: bestsellers-amazon
frameworkVersion: '2'

provider:
  name: aws
  apiName: bestsellers-amazon
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  layers:
    - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:25



functions:
  atualizar:
    handler: index.handler
    description: Realiza o web scraping na página de Bestsellers da Amazon
    events:
      - httpApi: 'GET /atualizarlista'
      - eventBridge:
          schedule: rate(1 day)
    timeout: 30
  listar:
    handler: listarBestsellers.handler
    description: Lista os 3 produtos mais vendidos da Amazon
    events:
     - httpApi: 'GET /'  
    timeout: 30

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: bestsellers-amazon
